fix paths

diff --git a/prepare_env b/prepare_env
--- a/prepare_env
+++ b/prepare_env
@@ -13,7 +13,15 @@ d=~/rawdisk2/sh
 dhi="$d/org.kde.syntax-highlighting"
 mkdir -p "$dhi" "$dhi/themes"
 cp ~/game/org.kde.syntax-highlighting/themes/my.theme "$dhi/themes"
-ln -s "$base/data/syntax/" "$dhi"
+
+if [ $# -eq 0 ]; then
+  ln -s "$base/data/syntax/" "$dhi"
+else
+  mkdir -p "$dhi/syntax"
+  for f in "$@"; do
+    [ -f "$base/data/syntax/$f.xml" ] && ln -s "$base/data/syntax/$f.xml" "$dhi/syntax" || echo "$f" error
+  done
+fi
 
 ln -s "$base/"* "$d"
 cd "$d"
@@ -69,7 +77,7 @@ chmod +x update-reference-data.sh hi.sh ihi.sh thi.sh tihi.sh nhi.sh nihi.sh tes
 
 ln -s "$base"/autotests/input/ "$base"/data/syntax/ .
 
-[ $# -eq 1 ] && cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ..
+# [ $# -eq 1 ] && cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ..
 
 echo -e '\e[33m'
 echo "cd $d/b"
diff --git a/prepare_syntax b/prepare_syntax
--- a/prepare_syntax
+++ b/prepare_syntax
@@ -8,8 +8,7 @@ if [ ! -d "$dhi" ] ; then
   cp ~/game/org.kde.syntax-highlighting/themes/my.theme "$dhi/themes"
 fi
 
-base="$(realpath "$(dirname "$0")")"
-base="${base%/*}"
+base=$PWD
 for f in "$@"; do
-  ln -s "$base/data/syntax/$f.xml" "$dhi/syntax"
+  [ -f "$base/data/syntax/$f.xml" ] && ln -s "$base/data/syntax/$f.xml" "$dhi/syntax" || echo "$f" error
 done
